#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CustomTabsClientApplication.Resource", IsApplication=true)]

namespace CustomTabsClientApplication
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int slide_in_left = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int slide_in_right = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int slide_out_left = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int slide_out_right = 2131034115;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_arrow_back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_play = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_share = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_stop = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int connect_button = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int cover = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int edit = 2131230720;
			
			// aapt resource value: 0x7f080005
			public const int launch_button = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int may_launch_button = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int play_pause = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int spinner = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int warmup_button = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int remote_view = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int amazing_grace = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int connect_button_text = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int launch_button_text = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int may_launch_button_text = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int url_hint = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int warmup_button_text = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
