//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("SushiHangover.GoogleChrome.CustomTabs.Shared")]
[assembly: AssemblyVersion("0.1.0")]
[assembly: AssemblyFileVersion("0.1.0")]
[assembly: AssemblyInformationalVersion("0.1.0-AppVeyor.1+Branch.AppVeyor.Sha.fa833b82e41cf57d3a659c3414e5a072784992e3")]
[assembly: AssemblyCopyright("Copyright (c) SushiHangover/RobertN")]

